demo_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      port: 5432
      user: "{{ env_var('DBT_USER', 'admin') }}"
      password: "{{ env_var('DBT_PASSWORD', 'admin') }}"
      dbname: "{{ env_var('DBT_DBNAME', 'analytics_demo') }}"
      schema: bronze        # default schema (models override via +schema in dbt_project.yml)
      threads: 4
